### ISSUE TITLE
wayland discussion

### ISSUE THREAD

**Issue by 0323pin** [jzbor/marswm#12]
Hi,

Hope you are doing fine.

First of all, this is not really an issue but, there's no _Discussions_ tab on this repository, so here we go :)

I've just had a crazy thought and decided to share it with you.
If you would like to support wayland without going through the trouble of writing a weston plug-in or, wlroots, I've just remembered [swc](https://github.com/michaelforney/swc).

Actually, support for NetBSD [has been added](https://github.com/michaelforney/swc/blob/master/libswc/seat-ws.c), which means I could test it.

Feel free to close this, the whole point was to tell you about `swc`, nothing else.
Besides, wayland on NetBSD is rather far away from being fully useful. It works with `swc`+`velox` but, it's buggy.
Regards

**Comment by jzbor** [comment]
Hi,
Thanks for the input. I have been thinking about wayland support, but it seems to be quite difficult to get right, especially with C bindings, as they don't always play nicely with Rust's ownership concept. This is the reason, why Waycooler for example gave up on Rust alltogether [[1](https://way-cooler.org/blog/2019/04/29/rewriting-way-cooler-in-c.html)]. 

I have been looking a little into [Smithay](https://github.com/Smithay/smithay), especially its [desktop API](https://smithay.github.io/smithay/smithay/desktop/index.html). However it does not seem very stable yet, as there has not been any release since two years. It is under (heavy) development though, which makes me optimistic that it will be a good fit in the future, especially if System76 sticks to using it for their compositor.

I want to make clear, that a wayland backend is a lot of work and even if/when I find the time to get started it will probably take quite some time until it is usable on a daily basis. Nevertheless feedback and input is always much appreciated!

Hope you have a nice day :)

**Comment by 0323pin** [comment]
Agreed, the easiest is probably to wait for System76, PopOS! and the cosmic DE. Most probably they will want to support wayland.

> I want to make clear, that a wayland backend is a lot of work and even if/when I find the time to get started it will probably take quite some time until it is usable on a daily basis.

I understand that. Personally, I've lost interest in wayland sometime ago, it has been _"the future"_ for a rather long time. Besides, I can see X being updated rather often, which contradicts what some have been preaching about it being dead.

Closing this issue now.
