### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by 0323pin** [jzbor/marswm#13]
Hi,

You are probably aware of this but there are broken links in the README.md
I haven't tried every single one of them but, `For a guide on how to setup a working desktop environment with marswm as base take a look at [SETUP.md](./SETUP.md).` this is broken and does not link to _e.g._ `/docs/installation.md`

Regards,

P.S.: I'm still using `marswm` on NetBSD 👍

**Comment by jzbor** [comment]
Thanks for the hint. I was aware that there are probably still some broken links, although I didn't know all of the exact ones. I tried transitioning to an [mdbook/online-first documentation](https://jzbor.de/marswm), because I didn't think the way it was until now was very clean. Now this does require mdbook in order to build offline documentation, but I think overall it makes for a more coherent documentation structure. I would be really interested in your opinion on this, as I am not yet fully settled on this solution.

I am happy to here you are still using it. I hope it works well for you. I have now added a [quickstart guide](https://jzbor.de/marswm/quickstart.html) in order for folks to get to a running system fast. Although it is strongly opinionated on Linux+systemd I would be grateful for your feedback there as well.

Thanks for all the great feedback ;)

**Comment by 0323pin** [comment]
I'm very happy with `marswm` and have no plans to change again on NetBSD. On my Linux system (Void musl) I'm using `leftwm`.

As for your quick start guide, I'm sure it will be appreciated by potential new users. But, I know nothing about `systemd` and I prefer it that way. Also, I don't use `pulseaudio` on any of my systems.

My NetBSD, where I spend most of my time, is not really standard. Appart from `marswm` built from git-HEAD, I use `elvish` as my login shell and `alacritty` also built from git-HEAD. `feh` as the wallpaper setter, `oh-my-posh` as shell prompt and a few other things settings environment variables at login in a rather non-standard way.

But, I'll keep an eye and let you know if I find more things.

**Comment by jzbor** [comment]
I think this can be closed, as it was addressed in c9c5967c68e5942d4a9e95474fe871311a18be43.
